name: Update Fuel Data

on:
  schedule:
    - cron: '1 2 * * *'  # esegui alle 00:00 ogni giorno

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # se hai delle dipendenze da installare

    - name: Run script
      run: python csv_merge_3.py  # sostituisci con il nome del tuo script

    - name: Commit and push
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add .
        git commit -m "Daily data update"
        git push
