name: Update CSV Data and Merge

on:
  schedule:
    - cron: '22 15 * * *'  # Esegue alle 11:45 AM ora italiana (UTC+2)
  workflow_dispatch: 

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout del codice sorgente
    - name: Checkout repository
      uses: actions/checkout@v2

    # Configura Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Installa le dipendenze
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    # Esegue lo script per unire i CSV
    - name: Merge CSV data
      run: python ./csv_merge_3.py

    # Configura Git con PAT
    - name: Setup Git with PAT
      run: git config --global url."https://${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

    # Fai il commit e il push dei cambiamenti
    - name: Commit and Push changes
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add merged_data.json
        git commit -m "Daily data update"
        git push origin HEAD:main
